// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIl4pKeuCd07f4YKZxreLIJoKPTPxicMU',
    appId: '1:558499448097:web:2da2625f8f8a49aff22a60',
    messagingSenderId: '558499448097',
    projectId: 'aarthik-setu',
    authDomain: 'aarthik-setu.firebaseapp.com',
    storageBucket: 'aarthik-setu.appspot.com',
    measurementId: 'G-2784LS56V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh1zxmKuIWU9ptZg43KI8SS5b70kxZgeM',
    appId: '1:558499448097:android:1d972a251b47ce35f22a60',
    messagingSenderId: '558499448097',
    projectId: 'aarthik-setu',
    storageBucket: 'aarthik-setu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkjArtJ_pRB5wAl6bTs8Vn77O9Dx4mzY',
    appId: '1:558499448097:ios:94bedcb3643f4d33f22a60',
    messagingSenderId: '558499448097',
    projectId: 'aarthik-setu',
    storageBucket: 'aarthik-setu.appspot.com',
    iosBundleId: 'com.harentortoise.aarthiksetu.aarthikSetu',
  );
}
