import 'package:file_picker/file_picker.dart';

import '../models/common/bank_details.dart';
import '../models/loan_applications/personal/forms/basic_details.dart';
import '../models/loan_applications/personal/forms/contact_details.dart';
import '../models/loan_applications/personal/forms/credit_info.dart';
import '../models/loan_applications/personal/forms/employment_details.dart';
import '../models/loan_applications/personal/forms/final_loan_form.dart';
import '../models/loan_applications/personal/forms/manual_itr_personal.dart';
import '../models/loan_applications/personal/personal_profile.dart';

class DummyPersonalReviewForm {
  static List<PersonalProfile> dummyPersonalProfiles = [
    PersonalProfile(
      id: 'personal_001',
      userId: 'user_001',
      name: 'John Doe',
      pan: 'ABCDE1234F',
    ),
    PersonalProfile(
      id: 'personal_002',
      userId: 'user_002',
      name: 'Jane Smith',
      pan: 'FGHIJ5678K',
    ),
    PersonalProfile(
      id: 'personal_003',
      userId: 'user_003',
      name: 'Amit Patel',
      pan: 'LMNOP9012R',
    ),
  ];

  static List<ManualItrPersonal> dummyManualItrData = [
    ManualItrPersonal(
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_001',
      id: 'itr_001',
      firstName: 'Rajesh',
      middleName: 'Kumar',
      lastName: 'Singh',
      dob: DateTime(1990, 6, 15),
      pan: 'ABCDE1234F',
      mobile: '9876543210',
      email: 'rajesh@example.com',
      addressLine1: '123 Main St.',
      addressLine2: 'Apt 101',
      landmark: 'Near Central Park',
      country: 'India',
      pinCode: '110001',
      state: 'Delhi',
      city: 'Delhi',
      village: null,
      district: 'Central Delhi',
      subDistrict: 'Delhi',
      netAnnualIncomeOne: MapEntry(
        FinancialYear(startYear: 2022, endYear: 2023),
        900000.0,
      ),
      netAnnualIncomeTwo: MapEntry(
        FinancialYear(startYear: 2021, endYear: 2022),
        800000.0,
      ),
      netAnnualIncomeThree: MapEntry(
        FinancialYear(startYear: 2020, endYear: 2021),
        750000.0,
      ),
    ),
    ManualItrPersonal(
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_002',
      id: 'itr_002',
      firstName: 'Sneha',
      middleName: 'Ravi',
      lastName: 'Patel',
      dob: DateTime(1985, 3, 22),
      pan: 'FGHIJ5678K',
      mobile: '9876543211',
      email: 'sneha@example.com',
      addressLine1: '456 Elm St.',
      addressLine2: 'Apt 202',
      landmark: 'Near City Mall',
      country: 'India',
      pinCode: '400001',
      state: 'Maharashtra',
      city: 'Mumbai',
      village: null,
      district: 'Mumbai',
      subDistrict: 'Kandivali',
      netAnnualIncomeOne: MapEntry(
        FinancialYear(startYear: 2021, endYear: 2022),
        1200000.0,
      ),
      netAnnualIncomeTwo: MapEntry(
        FinancialYear(startYear: 2020, endYear: 2021),
        1000000.0,
      ),
      netAnnualIncomeThree: MapEntry(
        FinancialYear(startYear: 2019, endYear: 2020),
        900000.0,
      ),
    ),
    ManualItrPersonal(
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_003',
      id: 'itr_003',
      firstName: 'Amit',
      middleName: 'Ramesh',
      lastName: 'Sharma',
      dob: DateTime(1988, 8, 10),
      pan: 'LMNOP9012R',
      mobile: '9876543212',
      email: 'amit@example.com',
      addressLine1: '789 Pine St.',
      addressLine2: null,
      landmark: 'Near Tech Park',
      country: 'India',
      pinCode: '560001',
      state: 'Karnataka',
      city: 'Bangalore',
      village: null,
      district: 'Bangalore',
      subDistrict: 'Bangalore South',
      netAnnualIncomeOne: MapEntry(
        FinancialYear(startYear: 2021, endYear: 2022),
        950000.0,
      ),
      netAnnualIncomeTwo: null,
      netAnnualIncomeThree: null,
    ),
  ];

  static List<BankDetails> dummyBankDetails = [
    BankDetails(
      id: 'bankDetail1',
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_0',
      bankName: 'Bank of Example',
      salaryAccount: true,
      accountSinceMonth: DateTime(2020, 1, 1),
      accountSinceYear: DateTime(2020, 1, 1),
      bankAccountStatementOne: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_jan_2024.pdf',
          path: '/path/to/bank_statement_jan_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementTwo: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_feb_2024.pdf',
          path: '/path/to/bank_statement_feb_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementThree: null,
    ),
    BankDetails(
      id: 'bankDetail2',
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_2',
      bankName: 'Sample Bank',
      salaryAccount: false,
      accountSinceMonth: DateTime(2018, 5, 1),
      accountSinceYear: DateTime(2018, 5, 1),
      bankAccountStatementOne: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_mar_2024.pdf',
          path: '/path/to/bank_statement_mar_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementTwo: null,
      bankAccountStatementThree: null,
    ),
    BankDetails(
      id: 'bankDetail3',
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_3',
      bankName: 'Example Credit Union',
      salaryAccount: true,
      accountSinceMonth: DateTime(2019, 11, 1),
      accountSinceYear: DateTime(2019, 11, 1),
      bankAccountStatementOne: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_apr_2024.pdf',
          path: '/path/to/bank_statement_apr_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementTwo: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_may_2024.pdf',
          path: '/path/to/bank_statement_may_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementThree: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_jun_2024.pdf',
          path: '/path/to/bank_statement_jun_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
    ),
  ];

  static List<BasicDetails> dummyBasicDetailsData = [
    BasicDetails(
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_001',
      salutation: 'Mr.',
      firstName: 'Rajesh',
      middleName: 'Kumar',
      lastName: 'Singh',
      dob: DateTime(1985, 5, 20),
      pan: 'ABCDE1234F',
      gender: 'Male',
      category: 'General',
      mobile: '9876543210',
      telephone: '011-12345678',
      emailPersonal: 'rajesh.singh@example.com',
      fatherName: 'Ramesh Singh',
      educationQualification: 'MBA',
      netWorth: 1500000.0,
      nationality: 'Indian',
      dependent: '2',
      maritalStatus: 'Married',
    ),
    BasicDetails(
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_002',
      salutation: 'Ms.',
      firstName: 'Sneha',
      middleName: null,
      lastName: 'Patel',
      dob: DateTime(1990, 8, 15),
      pan: 'FGHIJ5678K',
      gender: 'Female',
      category: 'OBC',
      mobile: '9876543211',
      telephone: '011-87654321',
      emailPersonal: 'sneha.patel@example.com',
      fatherName: 'Vijay Patel',
      educationQualification: 'B.Com',
      netWorth: 800000.0,
      nationality: 'Indian',
      dependent: '1',
      maritalStatus: 'Single',
    ),
    BasicDetails(
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_003',
      salutation: 'Mr.',
      firstName: 'Amit',
      middleName: 'Ramesh',
      lastName: 'Sharma',
      dob: DateTime(1988, 12, 10),
      pan: 'LMNOP9012R',
      gender: 'Male',
      category: 'SC',
      mobile: '9876543212',
      telephone: '011-23456789',
      emailPersonal: 'amit.sharma@example.com',
      fatherName: 'Krishna Sharma',
      educationQualification: 'B.Tech',
      netWorth: 2000000.0,
      nationality: 'Indian',
      dependent: '0',
      maritalStatus: 'Married',
    ),
  ];

  static List<EmploymentDetails> dummyEmploymentDetailsData = [
    EmploymentDetails(
      employmentType: 'Full-time',
      employerStatus: 'Private',
      designation: 'Software Engineer',
      modeOfSalary: 'Monthly',
      grossMonthlyIncome: '80000',
      netMonthlyIncome: '60000',
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_001',
      id: 'emp_001',
    ),
    EmploymentDetails(
      employmentType: 'Part-time',
      employerStatus: 'Self-employed',
      designation: 'Freelance Graphic Designer',
      modeOfSalary: 'Monthly',
      grossMonthlyIncome: '50000',
      netMonthlyIncome: '40000',
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_002',
      id: 'emp_002',
    ),
    EmploymentDetails(
      employmentType: 'Contract',
      employerStatus: 'Government',
      designation: 'Project Manager',
      modeOfSalary: 'Quarterly',
      grossMonthlyIncome: '120000',
      netMonthlyIncome: '90000',
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_003',
      id: 'emp_003',
    ),
  ];

  static List<CreditInfo> dummyCreditInfoData = [
    CreditInfo(
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_001',
      creditInfoUnits: [
        CreditInfoUnit(
          loanType: 'Personal Loan',
          lender: 'Bank A',
          sanctionedAmount: '500000',
          outstandingAmount: '300000',
          emiAmount: '15000',
        ),
        CreditInfoUnit(
          loanType: 'Home Loan',
          lender: 'Bank B',
          sanctionedAmount: '1500000',
          outstandingAmount: '1200000',
          emiAmount: '25000',
        ),
      ],
    ),
    CreditInfo(
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_002',
      creditInfoUnits: [
        CreditInfoUnit(
          loanType: 'Car Loan',
          lender: 'Bank C',
          sanctionedAmount: '700000',
          outstandingAmount: '400000',
          emiAmount: '20000',
        ),
        CreditInfoUnit(
          loanType: 'Education Loan',
          lender: 'Bank D',
          sanctionedAmount: '300000',
          outstandingAmount: '250000',
          emiAmount: '10000',
        ),
      ],
    ),
    CreditInfo(
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_003',
      creditInfoUnits: [
        CreditInfoUnit(
          loanType: 'Business Loan',
          lender: 'Bank E',
          sanctionedAmount: '1000000',
          outstandingAmount: '800000',
          emiAmount: '30000',
        ),
      ],
    ),
  ];

  static List<ContactDetails> dummyContactDetailsData = [
    ContactDetails(
      addressLine1: '123 Main St',
      addressLine2: 'Apt 4B',
      landmark: 'Near City Park',
      country: 'India',
      state: 'Maharashtra',
      city: 'Mumbai',
      pinCode: '400001',
      village: null,
      district: 'Mumbai',
      subDistrict: 'Greater Mumbai',
      typeOfResidence: 'Apartment',
      residenceSince: DateTime(2020, 1, 15),
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_001',
      id: 'contact_001',
    ),
    ContactDetails(
      addressLine1: '456 Market St',
      addressLine2: 'Ground Floor',
      landmark: 'Opposite Central Mall',
      country: 'India',
      state: 'Karnataka',
      city: 'Bangalore',
      pinCode: '560001',
      village: null,
      district: 'Bangalore',
      subDistrict: 'Bangalore South',
      typeOfResidence: 'House',
      residenceSince: DateTime(2018, 6, 20),
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_002',
      id: 'contact_002',
    ),
    ContactDetails(
      addressLine1: '789 Oak St',
      addressLine2: 'Floor 3',
      landmark: 'Near Old Bridge',
      country: 'India',
      state: 'Tamil Nadu',
      city: 'Chennai',
      pinCode: '600001',
      village: 'Thiruvallur',
      district: 'Chennai',
      subDistrict: 'Chennai South',
      typeOfResidence: 'Villa',
      residenceSince: DateTime(2021, 3, 10),
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_003',
      id: 'contact_003',
    ),
  ];

  static List<FinalLoanFormPersonal> dummyLoanForms = [
    FinalLoanFormPersonal(
      id: 'loanform_001',
      profileId: 'personal_001',
      timestamp: DateTime.now(),
      applicationId: 'app_001',
      loanPurpose: 'Home Renovation',
      loanAmount: '500000',
      tenureYears: 10,
      interestRate: '7.5%',
      retirementAge: '60',
      emiBySalaryAccount: true,
      payOutstandingByTerminalPayments: false,
      paySalaryInSalaryAccount: true,
      issueLetterToYourEmployerToPayOutstandingLoan: true,
      issueLetterToYourEmployerToNotChangeSalaryAccount: false,
      repaymentMethod: 'Auto Debit',
    ),
    FinalLoanFormPersonal(
      id: 'loanform_002',
      profileId: 'personal_002',
      timestamp: DateTime.now(),
      applicationId: 'app_002',
      loanPurpose: 'Education',
      loanAmount: '300000',
      tenureYears: 5,
      interestRate: '6.5%',
      retirementAge: '65',
      emiBySalaryAccount: false,
      payOutstandingByTerminalPayments: true,
      paySalaryInSalaryAccount: false,
      issueLetterToYourEmployerToPayOutstandingLoan: false,
      issueLetterToYourEmployerToNotChangeSalaryAccount: true,
      repaymentMethod: 'Cheque',
    ),
    FinalLoanFormPersonal(
      id: 'loanform_003',
      profileId: 'personal_003',
      timestamp: DateTime.now(),
      applicationId: 'app_003',
      loanPurpose: 'Personal Expenses',
      loanAmount: '200000',
      tenureYears: 3,
      interestRate: '8.0%',
      retirementAge: '58',
      emiBySalaryAccount: true,
      payOutstandingByTerminalPayments: false,
      paySalaryInSalaryAccount: true,
      issueLetterToYourEmployerToPayOutstandingLoan: true,
      issueLetterToYourEmployerToNotChangeSalaryAccount: true,
      repaymentMethod: 'Online Transfer',
    ),
  ];
}