import 'package:file_picker/file_picker.dart';

import '../models/common/bank_details.dart';
import '../models/loan_applications/business/business_profile.dart';
import '../models/loan_applications/business/forms/components/business_details.dart';
import '../models/loan_applications/business/forms/components/main_partner.dart';
import '../models/loan_applications/business/forms/components/partner.dart';
import '../models/loan_applications/business/forms/file_itr_business.dart';
import '../models/loan_applications/business/forms/final_loan_form.dart';
import '../models/loan_applications/business/forms/gst_details.dart';
import '../models/loan_applications/business/forms/stakeholders_form.dart';
import '../models/loan_applications/personal/personal_profile.dart';

class DummyBusinessReviewForm {

  static List<BusinessProfile> dummyBusinessProfiles = [
    BusinessProfile(
      id: "business_001",
      userId: "user_001",
      name: "Tech Innovations Pvt Ltd",
      pan: "XYZ123456789",
    ),
    BusinessProfile(
      id: "business_002",
      userId: "user_002",
      name: "Green Agriculture Co.",
      pan: "ABC987654321",
    ),
    BusinessProfile(
      id: "business_003",
      userId: "user_003",
      name: "Quick Logistics Services",
      pan: "LMN543216789",
    ),
  ];


  static List<FileItrBusiness> dummyItrFileForms = [
    FileItrBusiness(
      profileId: "business_001",
      timestamp: DateTime.now(),
      applicationId: "app_0",
      firstItr: MapEntry(FinancialYear(startYear: 2018, endYear: 2019), "file_0_first.pdf"),
      secondItr: MapEntry(FinancialYear(startYear: 2019, endYear: 2020), "file_0_second.pdf"),
      thirdItr: MapEntry(FinancialYear(startYear: 2020, endYear: 2021), "file_0_third.pdf"),
      id: "id_0",
    ),
    FileItrBusiness(
      profileId: "business_002",
      timestamp: DateTime.now(),
      applicationId: "app_1",
      firstItr: MapEntry(FinancialYear(startYear: 2018, endYear: 2019), "file_1_first.pdf"),
      secondItr: MapEntry(FinancialYear(startYear: 2019, endYear: 2020), "file_1_second.pdf"),
      thirdItr: MapEntry(FinancialYear(startYear: 2020, endYear: 2021), "file_1_third.pdf"),
      id: "id_1",
    ),
    FileItrBusiness(
      profileId: "business_003",
      timestamp: DateTime.now(),
      applicationId: "app_2",
      firstItr: MapEntry(FinancialYear(startYear: 2018, endYear: 2019), "file_2_first.pdf"),
      secondItr: MapEntry(FinancialYear(startYear: 2019, endYear: 2020), "file_2_second.pdf"),
      thirdItr: MapEntry(FinancialYear(startYear: 2020, endYear: 2021), "file_2_third.pdf"),
      id: "id_2",
    ),
  ];

  static List<GSTDetails> dummyGSTDetails = [
    GSTDetails(
      id: "id_0",
      profileId: "business_001",
      timestamp: DateTime.now(),
      applicationId: "app_0",
      gstNumber: "27AAEPM1234F1ZJ",
      gstUsername: "User_0",
      city: "Mumbai",
      verified: true,
      updateOn: DateTime.now(),
      totalPurchase: 500000.0,
      totalSales: 750000.0,
      gstSince: DateTime(2017, 7, 1),
    ),
    GSTDetails(
      id: "id_1",
      profileId: "business_002",
      timestamp: DateTime.now(),
      applicationId: "app_1",
      gstNumber: "29AABCM9876K1ZV",
      gstUsername: "User_1",
      city: "Bangalore",
      verified: true,
      updateOn: DateTime.now(),
      totalPurchase: 300000.0,
      totalSales: 450000.0,
      gstSince: DateTime(2018, 5, 12),
    ),
    GSTDetails(
      id: "id_2",
      profileId: "business_003",
      timestamp: DateTime.now(),
      applicationId: "app_2",
      gstNumber: "07AAJPG5678R1ZA",
      gstUsername: "User_2",
      city: "Delhi",
      verified: false,
      updateOn: DateTime.now(),
      totalPurchase: 200000.0,
      totalSales: 300000.0,
      gstSince: DateTime(2019, 11, 8),
    ),
  ];

  static List<BankDetails> dummyBankDetails = [
    BankDetails(
      id: 'bankDetail1',
      profileId: 'business_001',
      timestamp: DateTime.now(),
      applicationId: 'app_0',
      bankName: 'Bank of Example',
      salaryAccount: true,
      accountSinceMonth: DateTime(2020, 1, 1),
      accountSinceYear: DateTime(2020, 1, 1),
      bankAccountStatementOne: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_jan_2024.pdf',
          path: '/path/to/bank_statement_jan_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementTwo: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_feb_2024.pdf',
          path: '/path/to/bank_statement_feb_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementThree: null,
    ),
    BankDetails(
      id: 'bankDetail2',
      profileId: 'business_002',
      timestamp: DateTime.now(),
      applicationId: 'app_2',
      bankName: 'Sample Bank',
      salaryAccount: false,
      accountSinceMonth: DateTime(2018, 5, 1),
      accountSinceYear: DateTime(2018, 5, 1),
      bankAccountStatementOne: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_mar_2024.pdf',
          path: '/path/to/bank_statement_mar_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementTwo: null,
      bankAccountStatementThree: null,
    ),
    BankDetails(
      id: 'bankDetail3',
      profileId: 'business_003',
      timestamp: DateTime.now(),
      applicationId: 'app_3',
      bankName: 'Example Credit Union',
      salaryAccount: true,
      accountSinceMonth: DateTime(2019, 11, 1),
      accountSinceYear: DateTime(2019, 11, 1),
      bankAccountStatementOne: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_apr_2024.pdf',
          path: '/path/to/bank_statement_apr_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementTwo: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_may_2024.pdf',
          path: '/path/to/bank_statement_may_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
      bankAccountStatementThree: FilePickerResult([
        PlatformFile(
          name: 'bank_statement_jun_2024.pdf',
          path: '/path/to/bank_statement_jun_2024.pdf',
          size: 102400,
          bytes: null,
        ),
      ]),
    ),
  ];

  static List<StakeholdersForm> dummyStakeholdersData = [
    StakeholdersForm(
      id: 'stakeholder_1',
      profileId: 'business_001',
      timestamp: DateTime.now(),
      applicationId: 'app_0',
      businessDetails: BusinessDetails(
        addressLineOne: '123 Business St.',
        addressLineTwo: 'Suite 100',
        landmark: 'Near Central Park',
        pinCode: '123456',
        country: 'India',
        state: 'Maharashtra',
        city: 'Mumbai',
        district: 'Mumbai',
        subDistrict: 'Kandivali',
        village: 'Kandivali',
        month: 10,
        year: 2024,
      ),
      partners: [
        Partner(
          relationType: 'Co-Founder',
          ownershipPercentage: 50.0,
          salutation: 'Mr.',
          firstName: 'Rahul',
          middleName: 'Kumar',
          lastName: 'Sharma',
          fatherName: 'Vikram Sharma',
          gender: 'Male',
          dob: DateTime(1985, 5, 20),
          mobile: '9876543210',
          residentialStatus: 'Own',
          pan: 'ABCDE1234F',
          educationStatus: 'Graduate',
          totalExperienceInYears: 10,
          netWorth: 1000000.00,
          addressLine1: '456 Partner St.',
          addressLine2: 'Apt 202',
          landmark: 'Near City Mall',
          pinCode: '654321',
          village: 'Kandivali',
          district: 'Mumbai',
          subDistrict: 'Kandivali',
          country: 'India',
          state: 'Maharashtra',
          city: 'Mumbai',
          visuallyImpaired: 'No',
          isAGuarantor: true,
        ),
      ],
      mainPartner: MainPartner(
        name: 'Anita Gupta',
        owningAHouse: true,
        assessedForIncomeTax: true,
        haveALifeInsurancePolicy: true,
        maritalStatus: 'Married',
        spouseName: 'Rajesh Gupta',
        noOfChildren: 2,
      ),
    ),
    StakeholdersForm(
      id: 'stakeholder_2',
      profileId: 'business_002',
      timestamp: DateTime.now(),
      applicationId: 'app_1',
      businessDetails: BusinessDetails(
        addressLineOne: '789 Enterprise Ave.',
        addressLineTwo: null,
        landmark: 'Near Metro Station',
        pinCode: '789012',
        country: 'India',
        state: 'Delhi',
        city: 'New Delhi',
        district: 'New Delhi',
        subDistrict: 'Connaught Place',
        village: 'Connaught Place',
        month: 10,
        year: 2024,
      ),
      partners: [
        Partner(
          relationType: 'Investor',
          ownershipPercentage: 30.0,
          salutation: 'Ms.',
          firstName: 'Sneha',
          middleName: 'K.',
          lastName: 'Verma',
          fatherName: 'Ajay Verma',
          gender: 'Female',
          dob: DateTime(1990, 8, 15),
          mobile: '9123456789',
          residentialStatus: 'Rented',
          pan: 'FGHIJ5678K',
          educationStatus: 'Postgraduate',
          totalExperienceInYears: 5,
          netWorth: 500000.00,
          addressLine1: '1234 Investor Rd.',
          addressLine2: null,
          landmark: 'Near City Library',
          pinCode: '890123',
          village: 'Connaught Place',
          district: 'New Delhi',
          subDistrict: 'Connaught Place',
          country: 'India',
          state: 'Delhi',
          city: 'New Delhi',
          visuallyImpaired: 'No',
          isAGuarantor: false,
        ),
      ],
      mainPartner: MainPartner(
        name: 'Rahul Singh',
        owningAHouse: false,
        assessedForIncomeTax: true,
        haveALifeInsurancePolicy: false,
        maritalStatus: 'Single',
        spouseName: '',
        noOfChildren: 0,
      ),
    ),

    StakeholdersForm(
      id: 'stakeholder_3',
      profileId: 'business_003',
      timestamp: DateTime.now(),
      applicationId: 'app_2',
      businessDetails: BusinessDetails(
        addressLineOne: '101 Startup Blvd.',
        addressLineTwo: 'Floor 1',
        landmark: 'Near Innovation Hub',
        pinCode: '345678',
        country: 'India',
        state: 'Karnataka',
        city: 'Bengaluru',
        district: 'Bengaluru Urban',
        subDistrict: 'Koramangala',
        village: 'Koramangala',
        month: 10,
        year: 2024,
      ),
      partners: [
        Partner(
          relationType: 'Co-Owner',
          ownershipPercentage: 40.0,
          salutation: 'Dr.',
          firstName: 'Nisha',
          middleName: 'R.',
          lastName: 'Mehta',
          fatherName: 'Suresh Mehta',
          gender: 'Female',
          dob: DateTime(1988, 12, 5),
          mobile: '9988776655',
          residentialStatus: 'Owned',
          pan: 'XYZAB1234C',
          educationStatus: 'Doctorate',
          totalExperienceInYears: 8,
          netWorth: 2000000.00,
          addressLine1: '456 Healthcare Rd.',
          addressLine2: null,
          landmark: 'Near Medical College',
          pinCode: '567890',
          village: 'Koramangala',
          district: 'Bengaluru Urban',
          subDistrict: 'Koramangala',
          country: 'India',
          state: 'Karnataka',
          city: 'Bengaluru',
          visuallyImpaired: 'No',
          isAGuarantor: true,
        ),
        Partner(
          relationType: 'Advisor',
          ownershipPercentage: 10.0,
          salutation: 'Mr.',
          firstName: 'Vikram',
          middleName: null,
          lastName: 'Patel',
          fatherName: 'Anil Patel',
          gender: 'Male',
          dob: DateTime(1980, 3, 22),
          mobile: '9876543210',
          residentialStatus: 'Rented',
          pan: 'LMNOP6789D',
          educationStatus: 'Postgraduate',
          totalExperienceInYears: 15,
          netWorth: 1500000.00,
          addressLine1: '789 Consultancy St.',
          addressLine2: null,
          landmark: 'Near Business Park',
          pinCode: '678901',
          village: 'Koramangala',
          district: 'Bengaluru Urban',
          subDistrict: 'Koramangala',
          country: 'India',
          state: 'Karnataka',
          city: 'Bengaluru',
          visuallyImpaired: 'No',
          isAGuarantor: false,
        ),
      ],
      mainPartner: MainPartner(
        name: 'Rahul Reddy',
        owningAHouse: true,
        assessedForIncomeTax: true,
        haveALifeInsurancePolicy: true,
        maritalStatus: 'Married',
        spouseName: 'Priya Reddy',
        noOfChildren: 1,
      ),
    ),
    StakeholdersForm(
      id: 'stakeholder_4',
      profileId: 'profile_004',
      timestamp: DateTime.now(),
      applicationId: 'app_004',
      businessDetails: BusinessDetails(
        addressLineOne: '202 Tech Lane',
        addressLineTwo: 'Ground Floor',
        landmark: 'Near Silicon Valley',
        pinCode: '789456',
        country: 'India',
        state: 'Telangana',
        city: 'Hyderabad',
        district: 'Hyderabad',
        subDistrict: 'HITEC City',
        village: 'HITEC City',
        month: 10,
        year: 2024,
      ),
      partners: [
        Partner(
          relationType: 'Shareholder',
          ownershipPercentage: 25.0,
          salutation: 'Mrs.',
          firstName: 'Aditi',
          middleName: 'N.',
          lastName: 'Saxena',
          fatherName: 'Raghav Saxena',
          gender: 'Female',
          dob: DateTime(1992, 6, 10),
          mobile: '9081726354',
          residentialStatus: 'Owned',
          pan: 'PQRST4567E',
          educationStatus: 'Graduate',
          totalExperienceInYears: 3,
          netWorth: 300000.00,
          addressLine1: '321 Investment St.',
          addressLine2: null,
          landmark: 'Near Financial District',
          pinCode: '654321',
          village: 'HITEC City',
          district: 'Hyderabad',
          subDistrict: 'HITEC City',
          country: 'India',
          state: 'Telangana',
          city: 'Hyderabad',
          visuallyImpaired: 'No',
          isAGuarantor: true,
        ),
      ],
      mainPartner: MainPartner(
        name: 'Vinay Choudhary',
        owningAHouse: false,
        assessedForIncomeTax: false,
        haveALifeInsurancePolicy: true,
        maritalStatus: 'Single',
        spouseName: '',
        noOfChildren: 0,
      ),
    ),
  ];

  static List<FinalLoanFormBusiness> dummyLoanForms = [
    FinalLoanFormBusiness(
      id: 'loan_form_1',
      profileId: 'business_001',
      timestamp: DateTime.now(),
      applicationId: 'app_0',
      industry: 'Manufacturing',
      sectorName: 'Textiles',
      subSectorName: 'Garments',
      msmeRegistrationNumber: 'MSME123456',
      udyogAadharNumber: 'UDYOG987654321',
      productDescription: 'Cotton garments for casual wear',
      collaterals: [
        Collateral(
          collateralType: 'Property',
          collateralAmount: 5000000.0,
        ),
        Collateral(
          collateralType: 'Inventory',
          collateralAmount: 2000000.0,
        ),
      ],
      loanAmountRequired: 7000000.0,
      promoterContribution: 1500000.0,
      purposeOfLoan: 'Expansion of manufacturing unit',
      projectSales: 3000000.0,
      businessISOCertified: true,
      factoryPremise: 'Owned',
      knowHow: 'Expertise in garment manufacturing and design',
      competition: 'Local and international garment manufacturers',
      existingLoans: [
        ExistingLoan(
          nameOfLender: 'Bank of India',
          sanctionedAmount: 3000000.0,
          outstandingAmount: 1500000.0,
          emiAmount: 50000.0,
          loanType: 'Term Loan',
          collateralAmount: 2500000.0,
          status: 'Active',
        ),
        ExistingLoan(
          nameOfLender: 'State Bank of India',
          sanctionedAmount: 2000000.0,
          outstandingAmount: 1000000.0,
          emiAmount: 40000.0,
          loanType: 'Working Capital',
          collateralAmount: 1000000.0,
          status: 'Active',
        ),
      ],
      existingLoanAmount: 2500000.0,
      additionalLoanRequired: 4500000.0,
      totalLoanAmount: 7000000.0,
    ),
    FinalLoanFormBusiness(
      id: 'loan_form_2',
      profileId: 'business_002',
      timestamp: DateTime.now(),
      applicationId: 'app_1',
      industry: 'Information Technology',
      sectorName: 'Software Development',
      subSectorName: 'Mobile Apps',
      msmeRegistrationNumber: 'MSME654321',
      udyogAadharNumber: 'UDYOG123456789',
      productDescription: 'Development of mobile applications for businesses',
      collaterals: [
        Collateral(
          collateralType: 'Bank Guarantee',
          collateralAmount: 1000000.0,
        ),
      ],
      loanAmountRequired: 3000000.0,
      promoterContribution: 800000.0,
      purposeOfLoan: 'Investment in technology and staffing',
      projectSales: 1500000.0,
      businessISOCertified: false,
      factoryPremise: 'Rented',
      knowHow: 'Strong background in software engineering',
      competition: 'Other software development firms in the region',
      existingLoans: [
        ExistingLoan(
          nameOfLender: 'HDFC Bank',
          sanctionedAmount: 1000000.0,
          outstandingAmount: 500000.0,
          emiAmount: 25000.0,
          loanType: 'Personal Loan',
          collateralAmount: 500000.0,
          status: 'Settled',
        ),
      ],
      existingLoanAmount: 500000.0,
      additionalLoanRequired: 2500000.0,
      totalLoanAmount: 3000000.0,
    ),

    FinalLoanFormBusiness(
      id: 'loan_form_3',
      profileId: 'business_003',
      timestamp: DateTime.now(),
      applicationId: 'app_2',
      industry: 'Agriculture',
      sectorName: 'Organic Farming',
      subSectorName: 'Vegetable Production',
      msmeRegistrationNumber: 'MSME789012',
      udyogAadharNumber: 'UDYOG234567890',
      productDescription: 'Production and distribution of organic vegetables',
      collaterals: [
        Collateral(
          collateralType: 'Farm Land',
          collateralAmount: 10000000.0,
        ),
        Collateral(
          collateralType: 'Machinery',
          collateralAmount: 3000000.0,
        ),
      ],
      loanAmountRequired: 8000000.0,
      promoterContribution: 2000000.0,
      purposeOfLoan: 'Purchase of seeds and fertilizers',
      projectSales: 5000000.0,
      businessISOCertified: false,
      factoryPremise: 'Owned',
      knowHow: 'Expertise in sustainable farming practices',
      competition: 'Local organic farms and markets',
      existingLoans: [
        ExistingLoan(
          nameOfLender: 'Punjab National Bank',
          sanctionedAmount: 4000000.0,
          outstandingAmount: 2000000.0,
          emiAmount: 60000.0,
          loanType: 'Agricultural Loan',
          collateralAmount: 2000000.0,
          status: 'Active',
        ),
        ExistingLoan(
          nameOfLender: 'ICICI Bank',
          sanctionedAmount: 1500000.0,
          outstandingAmount: 500000.0,
          emiAmount: 20000.0,
          loanType: 'Personal Loan',
          collateralAmount: 800000.0,
          status: 'Settled',
        ),
      ],
      existingLoanAmount: 2500000.0,
      additionalLoanRequired: 5500000.0,
      totalLoanAmount: 8000000.0,
    )
  ];

}

class DummyPersonalReviewForm {

  static List<PersonalProfile> dummyPersonalProfiles = [
    PersonalProfile(
      id: "1",
      userId: "user_001",
      name: "John Doe",
      pan: "ABCDE1234F",
    ),
    PersonalProfile(
      id: "2",
      userId: "user_002",
      name: "Jane Smith",
      pan: "FGHIJ5678K",
    ),
    PersonalProfile(
      id: "3",
      userId: "user_003",
      name: "Alice Johnson",
      pan: "LMNOP9876Q",
    ),
  ];



}
